### PR TITLE
pak install and add to minicran for further availability checks

### PR DESCRIPTION
**Pull request by pawelru**
alternative to https://github.com/insightsengineering/r-revdepcheck-action/pull/2

Main changes:
- use pak for installing
  - this will respect Remotes for non-CRAN dependent packages
  - for the package itself - try to derive GitHub ref for released version based on URL field from the DESCRIPTION file
- after pak install - look in the pkgcache and copy .tar.gz into miniCRAN so that it's findable by revdepcheck and anyone else

Fixes:
- printing empty report

### CODE REVIEW

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m7pr** [comment]
recheck

**Comment by m7pr** [comment]
CLA assistant failed with below issue

> Error: Could not retrieve repository contents. Status: 404

https://github.com/insightsengineering/r-revdepcheck-action/actions/runs/10663392597/job/29552480818#step:2:21

@cicdguy would you know what is the source of the problem?

image

**Comment by cicdguy** [comment]
> CLA assistant failed with below issue
> 
> 
> 
> > Error: Could not retrieve repository contents. Status: 404
> 
> 
> 
> https://github.com/insightsengineering/r-revdepcheck-action/actions/runs/10663392597/job/29552480818#step:2:21
> 
> 
> 
> @cicdguy would you know what is the source of the problem?
> 
> 
> 
> image
> 
> 

Known issue. Tagged you in relevant thread in chat. Feel free to ignore for now.

**Comment by m7pr** [comment]
Hey, once this is finalized and merged, please check if those 2 PR fix pipelines in 
- teal.goshawk https://github.com/insightsengineering/teal.goshawk/pull/306
- teal.osprey https://github.com/insightsengineering/teal.osprey/pull/280

**Comment by walkowif** [comment]
@m7pr I ran the revdepcheck workflow, and the results are as follows:
* [teal.goshawk](https://github.com/insightsengineering/teal.goshawk/actions/runs/10958680315/job/30429406892)
* [teal.osprey](https://github.com/insightsengineering/teal.osprey/actions/runs/10958678531/job/30429401106)

Feel free to re-trigger this workflow (after adding any updates to `insightsengineering/r-revdepcheck-action@fix_non_cran`) by going [here](https://github.com/insightsengineering/teal.goshawk/actions/workflows/scheduled.yaml) -> Run workflow -> Use workflow from: `fix-pipelines@main` -> Drop down: revdepcheck (similarly for teal.osprey).

After the testing is done, you can remove my commits from the PRs in teal.goshawk and teal.osprey.

**Comment by m7pr** [comment]
One workflow can't find package `goshawk` and the other can't find package `osprey`. So I guess this is still not done

**Pull request closed without merging**
